# Generated by Django 4.2 on 2024-09-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_rename_module_materials'),
        ('quizzes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='class_app.course'),
            preserve_default=False,
        ),
    ]
