# Generated by Django 4.2 on 2024-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='req_score_to_pass',
            field=models.FloatField(help_text='score to pass'),
        ),
    ]
